services:
  bot:
    build:
      context: .
      dockerfile: DEV.Dockerfile
    container_name: linkinzzz
    command: sh -c "watchfiles --filter python 'python run.py' core handlers utils run.py"
    env_file:
      - .env
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - .:/app
      - playwright-cache:/ms-playwright

volumes:
  playwright-cache: