services:
  linkinzzz-bot:
    image: ghcr.io/duckinzzz/linkinzzz-bot:latest
    container_name: linkinzzz-bot
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "8081"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"
    volumes:
      - ./cookies:/app/cookies
    mem_limit: 300m
    mem_reservation: 100m
    cpus: 0.20
    networks:
      - caddy-proxy
    labels:
      caddy: webhook.duckinzzz.ru
      caddy.handle: /linkinzzz*
      caddy.handle.reverse_proxy: "{{upstreams 8081}}"
      
networks:
  caddy-proxy:
    external: true
